package io.aduhtkjm.mekanismheated.content.obsidiandust;

import io.aduhtkjm.mekanismheated.item.ItemObsidianDust;
import mekanism.common.registration.impl.ItemDeferredRegister;
import mekanism.common.registration.impl.ItemRegistryObject;
import net.minecraft.world.item.Item;
import org.lwjgl.system.NonnullDefault;

/**
 * A flavour of obsidian dust: Mekanism's obsidian dust with a small icon of the metal it was condensed from in its
 * top-left corner.
 * <p>
 * That icon is a baked texture rather than something drawn at runtime. The item model stacks the shared
 * {@code mekanism:item/dust_obsidian} base with the variant's overlay as a second layer, so the overlay is just a
 * 16x16 texture that is transparent everywhere outside the 6x6 corner. Adding an ore is therefore one call to
 * {@link #register} here, the matching assets (the overlay generated by {@code scripts/obsidian_dust_overlay.py},
 * the item model, the lang entries) and a condensing recipe.
 * <p>
 * The assets follow the ore name: a variant registered as {@code "iron"} becomes the item
 * {@code mekanismheated:iron_obsidian_dust} and uses the overlay
 * {@code mekanismheated:textures/item/obsidian_dust/iron.png}.
 */
@NonnullDefault
public final class ObsidianDustVariant {

    /** The suffix every obsidian dust item's registry name ends with. */
    private static final String SUFFIX = "_obsidian_dust";

    /**
     * Registers a new obsidian dust variant.
     *
     * @param items   the item registry to register into.
     * @param ore     the ore the dust is condensed from, used for the registry name and the overlay texture.
     * @param formula the metal's formula (e.g. {@code "Fe"}), shown as the item's tooltip.
     */
    public static ObsidianDustVariant register(ItemDeferredRegister items, String ore, String formula) {
        return new ObsidianDustVariant(items, ore, formula);
    }

    private final ItemRegistryObject<ItemObsidianDust> item;

    private ObsidianDustVariant(ItemDeferredRegister items, String ore, String formula) {
        this.item = items.register(ore + SUFFIX, () -> new ItemObsidianDust(new Item.Properties(), formula));
    }

    public ItemRegistryObject<ItemObsidianDust> item() {
        return item;
    }
}
